### ISSUE TITLE
Link back to the original creator

### ISSUE THREAD

**Issue by tavurth** [StudioAdriatic/PGSGP#4]
Hi [Kristijan Draca](https://www.linkedin.com/in/kristijandraca/?originalSubdomain=hr), we noticed that you have forked Constantin Gisca's public MIT licensed repository, and removed the backlink to the original github sources.

Let's add a backlink there, and perhaps pull your changes to the main repository?

**Comment by kristijandraca** [comment]
Hi, 

this project is a fork of oneseedfruit/PGSGP and he forked project from cgisca's project.

Both projects are not actively maintained, and I don't see the point in having connections with them anymore.  I appreciated their work! I took this project because I saw that community needs a plugin that is more actively maintained. 

If you will feel better I will update README.md and put their links there, and I didn't reupload this project like mine, you can still see each and every contributor to this project.

**Comment by tavurth** [comment]
Thank you!
